
gres: gpu:1
partition: gpu
nodes: 1
ntasks-per-node: 1
time: 24:00:00
begin: now
job-name: VK_meta_sim
mail-type: END,FAIL
mail-user: antonio.gimenez-nadal@student.isae-supaero.fr
output: ./results/slurm.%j.out
error: ./results/slurm.%j.err

