
####################
#    SIMULATION    #
####################
simClass: VonKarman_rotative
GPU: True
sim_method: convnet # Choose between convnet and CG (as reference)

#Field saving options
save_field: True
save_field_x_ite: 50
save_post_x_ite: 50

#Plot options
plot_field: True
plot_x_ite: 50

#Post-computations options
post_computations: True

out_dir: './output/dir/'

####################
# PHYSICAL FORCES  #
####################
Reynolds: 100.0
Alpha: 0.0 # Rotating dimensionless parameter!

####################
#  DISCRETIZATION  #
####################
Nx: 896 #[] number of control volumes in x direction
Ny: 608 #[] number of control volumes in y direction
Nt: 10000 #[] number of time steps to simulate

# CFL
CFL: 0.2


####################
#    SOLVER IA     #
####################
ite_transition: 0
network_params:
  load_path: '/path/to/neurasim/trained_networks/lt_nograd_4_16/Unet_lt_nograd_4_16/'
  model_name: 'Unet_lt_nograd_4_16'
  new_train: 'new' # Option to read networks trained with older versions, not to be modified in this scope

####################
#  NORMALIZATION   #
####################
normalization:
  normalize: True
  scale_factor: 10.0
  debug_folder: './results/debug/'

####################
#     GEOMETRY     #
####################
#Domain
Lx: 300
Ly: 200

#BC
BC_domain_x: OPEN
BC_domain_y: STICKY

#Cilinder
D: 10
xD: 100
